{% set name = "son" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/son-{{ version }}.tar.gz
  sha256: d4f7afb24e9b532b428d6ef35a3bd778ad93e0c97b7f5e72857dc2b0d8439ae5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.5
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.5
    - lz >=0.11.0,<0.12.0

test:
  imports:
    - son
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://flokno.github.io/son/
  summary: Tools to read and write .son files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
